SECTION "Red Music Pointers", ROMX

INCLUDE "audio/music_red_pointers.asm"

SECTION "Red Music 1", ROMX

INCLUDE "audio/music/red_bikeriding.asm"
INCLUDE "audio/music/red_celadon.asm"
INCLUDE "audio/music/red_cinnabar.asm"
INCLUDE "audio/music/red_cinnabarmansion.asm"
INCLUDE "audio/music/red_cities1.asm"
INCLUDE "audio/music/red_cities2.asm"
INCLUDE "audio/music/red_credits.asm"
INCLUDE "audio/music/red_defeatedgymleader.asm"
INCLUDE "audio/music/red_defeatedtrainer.asm"
INCLUDE "audio/music/red_defeatedwildmon.asm"
INCLUDE "audio/music/red_dungeon1.asm"
INCLUDE "audio/music/red_dungeon2.asm"
INCLUDE "audio/music/red_dungeon3.asm"
INCLUDE "audio/music/red_finalbattle.asm"
INCLUDE "audio/music/red_gamecorner.asm"
INCLUDE "audio/music/red_gym.asm"
INCLUDE "audio/music/red_gymleaderbattle.asm"
INCLUDE "audio/music/red_halloffame.asm"
INCLUDE "audio/music/red_indigoplateau.asm"
INCLUDE "audio/music/red_introbattle.asm"
INCLUDE "audio/music/red_jigglypuffsong.asm"
INCLUDE "audio/music/red_lavender.asm"
INCLUDE "audio/music/red_meeteviltrainer.asm"

SECTION "Red Music 2", ROMX

INCLUDE "audio/music/red_meetfemaletrainer.asm"
INCLUDE "audio/music/red_meetmaletrainer.asm"
INCLUDE "audio/music/red_meetprofoak.asm"
INCLUDE "audio/music/red_meetrival.asm"
INCLUDE "audio/music/red_museumguy.asm"
INCLUDE "audio/music/red_oakslab.asm"
INCLUDE "audio/music/red_pallettown.asm"
INCLUDE "audio/music/red_pkmnhealed.asm"
INCLUDE "audio/music/red_pokecenter.asm"
INCLUDE "audio/music/red_pokemontower.asm"
INCLUDE "audio/music/red_routes1.asm"
INCLUDE "audio/music/red_routes2.asm"
INCLUDE "audio/music/red_routes3.asm"
INCLUDE "audio/music/red_routes4.asm"
INCLUDE "audio/music/red_safarizone.asm"
INCLUDE "audio/music/red_silphco.asm"
INCLUDE "audio/music/red_ssanne.asm"
INCLUDE "audio/music/red_surfing.asm"
INCLUDE "audio/music/red_titlescreen.asm"
INCLUDE "audio/music/red_trainerbattle.asm"
INCLUDE "audio/music/red_unusedsong.asm"
INCLUDE "audio/music/red_vermilion.asm"
INCLUDE "audio/music/red_wildbattle.asm"
